name: Node.js CVE Scanning

on:
  push:
    paths:
      - 'src/Finos.Fdc3.Backplane.Client.JS/package.json'
      - 'src/Finos.Fdc3.Backplane.Client.JS/package-lock.json'
      - 'src/Finos.Fdc3.Backplane.Client.JS/allow-list.json'
      - '.github/workflows/node-cve-scanning.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --prod
        working-directory: src/Finos.Fdc3.Backplane.Client.JS
      - run: npx --yes auditjs ossi --whitelist allow-list.json
        working-directory: src/Finos.Fdc3.Backplane.Client.JS
