name: NodeJS with Gulp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: package install
      run: |
        yarn install
      working-directory: ./src/Finos.Fdc3.Backplane.Client.JS
    - name: build
      run: |
        yarn build
      working-directory: ./src/Finos.Fdc3.Backplane.Client.JS
  
